"use client";
import {useEffect,useMemo,useState} from "react";
import {API,jfetch} from "../lib/api";

type V={rule_code:string;passed:boolean;severity:string;expected_value:string|null;actual_value:string|null;difference:number|null;message:string};
type I={id:number;invoice_number:string;po_number:string|null;supplier_name:string;invoice_date:string|null;currency:string;subtotal:number;tax:number;total:number;original_filename:string;status:string;risk_score:number;risk_level:string;explanation:string;recommendation:string;extraction_provider:string;created_at:string;items:any[];validations:V[]};
type D={total_invoices:number;auto_approved:number;review_required:number;rejected:number;total_value:number;exception_rate:number};
const empty:D={total_invoices:0,auto_approved:0,review_required:0,rejected:0,total_value:0,exception_rate:0};
function badge(s:string){return `badge ${s.toLowerCase().replaceAll("_","-")}`}
export default function Home(){
 const [invoices,setInvoices]=useState<I[]>([]),[dash,setDash]=useState<D>(empty),[selected,setSelected]=useState<I|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[tab,setTab]=useState("dashboard");
 async function refresh(selectId?:number){const [d,i]=await Promise.all([jfetch("/dashboard"),jfetch("/invoices")]);setDash(d);setInvoices(i);if(selectId)setSelected(i.find((x:I)=>x.id===selectId)||null);else if(selected)setSelected(i.find((x:I)=>x.id===selected.id)||null)}
 useEffect(()=>{refresh().catch(e=>setMsg(e.message))},[])
 async function seed(){setBusy(true);try{const r=await jfetch("/demo/seed",{method:"POST"});setMsg(`${r.message}. ${r.created_purchase_orders} PO(s) created.`);await refresh()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function upload(f:File){setBusy(true);setMsg("Extracting, matching and validating invoice...");try{const fd=new FormData();fd.append("file",f);const r=await jfetch("/invoices/upload",{method:"POST",body:fd});setSelected(r);setTab("invoices");setMsg(`Processed ${r.invoice_number}: ${r.status}`);await refresh(r.id)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function act(action:string){if(!selected)return;setBusy(true);try{await jfetch(`/invoices/${selected.id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actor:"finance.manager@example.com",note:`Decision from reviewer dashboard: ${action}`})});await refresh(selected.id)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const failures=useMemo(()=>selected?.validations.filter(v=>!v.passed)||[],[selected]);
 return <main>
  <aside><div className="brand"><div className="logo">IG</div><div><b>InvoiceGuard</b><span>AI AP Agent</span></div></div>
   <nav>{[["dashboard","◫","Dashboard"],["invoices","▤","Invoices"],["po","⌘","Purchase Orders"],["audit","◷","Audit trail"]].map(([k,ic,t])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}><i>{ic}</i>{t}</button>)}</nav>
   <div className="trust"><b>Auditable by design</b><p>Rules decide. AI extracts and explains.</p></div>
  </aside>
  <section className="shell"><header><div><h1>{tab==="dashboard"?"Accounts Payable Control Center":tab==="invoices"?"Invoice Review":tab==="po"?"Purchase Orders":"Audit Trail"}</h1><p>Explainable invoice-to-PO validation with deterministic controls.</p></div><div className="avatar">FM</div></header>
   {msg&&<div className="toast">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
   {tab==="dashboard"&&<><div className="actions"><label className="upload"><input type="file" accept=".pdf,.png,.jpg,.jpeg" disabled={busy} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><span>＋ Upload invoice</span></label><button className="secondary" disabled={busy} onClick={seed}>Load demo data</button></div>
    <div className="stats"><Stat label="Invoices processed" value={dash.total_invoices}/><Stat label="Auto approved" value={dash.auto_approved}/><Stat label="Needs review" value={dash.review_required}/><Stat label="Exception rate" value={`${dash.exception_rate}%`}/></div>
    <div className="grid"><div className="card wide"><div className="cardhead"><div><h2>Recent invoices</h2><p>Click any row to inspect evidence and findings.</p></div><b>${dash.total_value.toLocaleString(undefined,{maximumFractionDigits:2})}</b></div><InvoiceTable invoices={invoices} open={(x)=>{setSelected(x);setTab("invoices")}}/></div>
    <div className="card"><h2>How decisions work</h2><div className="pipeline"><Step n="1" t="Extract" d="PDF text / OCR → typed JSON"/><Step n="2" t="Match" d="PO + supplier + line items"/><Step n="3" t="Validate" d="Deterministic Python rules"/><Step n="4" t="Explain" d="AI summarizes exceptions"/></div></div></div></>}
   {tab==="invoices"&&<div className="review"><div className="card invoice-list"><div className="cardhead"><div><h2>Invoices</h2><p>{invoices.length} processed</p></div><label className="mini-upload">Upload<input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><InvoiceTable invoices={invoices} open={setSelected}/></div>
    <div className="card detail">{selected?<><div className="detailtop"><div><span className={badge(selected.status)}>{selected.status.replaceAll("_"," ")}</span><h2>{selected.invoice_number}</h2><p>{selected.supplier_name} · {selected.po_number||"No PO"} · via {selected.extraction_provider}</p></div><Risk score={selected.risk_score} level={selected.risk_level}/></div>
      <div className="money"><div><span>Invoice total</span><b>{selected.currency} {selected.total.toLocaleString()}</b></div><div><span>Subtotal</span><b>{selected.subtotal.toLocaleString()}</b></div><div><span>Tax</span><b>{selected.tax.toLocaleString()}</b></div></div>
      <h3>Validation evidence</h3><div className="findings">{selected.validations.map((v,i)=><div className={`finding ${v.passed?"ok":"bad"}`} key={i}><div className="mark">{v.passed?"✓":"!"}</div><div><b>{v.rule_code.replaceAll("_"," ")}</b><p>{v.message}</p>{!v.passed&&<small>Expected: {v.expected_value||"—"} · Actual: {v.actual_value||"—"}</small>}</div></div>)}</div>
      <div className="ai"><span>AI reviewer explanation</span><p>{selected.explanation}</p><b>Recommendation</b><p>{selected.recommendation}</p></div>
      <div className="decision"><button className="approve" disabled={busy} onClick={()=>act("approve")}>✓ Approve</button><button className="reject" disabled={busy} onClick={()=>act("reject")}>× Reject</button><button className="secondary" disabled={busy} onClick={()=>act("request-review")}>Request review</button><button className="secondary" onClick={()=>window.open(`${API}/invoices/${selected.id}/file`,`_blank`)}>Open original</button></div>
    </>:<div className="empty"><b>Select an invoice</b><p>Upload one or choose a row from the left.</p></div>}</div></div>}
   {tab==="po"&&<POView/>}{tab==="audit"&&<AuditView/>}
  </section>
 </main>}
function Stat({label,value}:{label:string,value:any}){return <div className="stat"><span>{label}</span><b>{value}</b></div>}
function InvoiceTable({invoices,open}:{invoices:I[],open:(x:I)=>void}){return <div className="table"><div className="tr th"><span>Invoice</span><span>Supplier</span><span>Total</span><span>Status</span></div>{invoices.length?invoices.map(x=><button className="tr" key={x.id} onClick={()=>open(x)}><span><b>{x.invoice_number}</b><small>{x.po_number||"No PO"}</small></span><span>{x.supplier_name}</span><span>{x.currency} {x.total.toLocaleString()}</span><span><i className={badge(x.status)}>{x.status.replaceAll("_"," ")}</i></span></button>):<div className="emptyrow">No invoices yet. Load demo data and upload a sample.</div>}</div>}
function Step({n,t,d}:{n:string,t:string,d:string}){return <div className="step"><em>{n}</em><div><b>{t}</b><p>{d}</p></div></div>}
function Risk({score,level}:{score:number,level:string}){return <div className="risk"><div className="ring" style={{"--score":`${score*3.6}deg`} as any}><b>{score}</b></div><span>{level} RISK</span></div>}
function POView(){const [pos,setPos]=useState<any[]>([]);useEffect(()=>{jfetch("/purchase-orders").then(setPos)},[]);return <div className="card"><div className="cardhead"><div><h2>Purchase orders</h2><p>System-of-record data used for deterministic matching.</p></div></div><div className="table"><div className="tr th"><span>PO</span><span>Supplier</span><span>Currency</span><span>Status</span></div>{pos.map(p=><div className="tr static" key={p.id}><span><b>{p.po_number}</b><small>{p.items.length} line(s)</small></span><span>{p.supplier_name}</span><span>{p.currency}</span><span><i className="badge auto-approved">{p.status}</i></span></div>)}</div></div>}
function AuditView(){const [logs,setLogs]=useState<any[]>([]);useEffect(()=>{jfetch("/audit-logs").then(setLogs)},[]);return <div className="card"><div className="cardhead"><div><h2>Decision history</h2><p>Immutable-style application audit events for the demo.</p></div></div><div className="auditlist">{logs.map(l=><div className="auditrow" key={l.id}><div className="dot"></div><div><b>{l.action}</b> · Invoice #{l.invoice_id||"—"}<p>{l.actor} · {new Date(l.created_at).toLocaleString()}</p><small>{l.note}</small></div></div>)}</div></div>}
